### ISSUE TITLE
How to register an Admin user?

### ISSUE THREAD

**Issue by rezaee** [zeeshan87/Server-side-Development-with-NodeJS-Express-and-MongoDB#2]
I am trying to sign up a new admin user using `{"username":"admin", "password":"123", "admin":"true"}` on `https://localhost:3443/users/signup` then after I got "Registration successful~" message I do loggin with that user and the `JWT-token` I got from previous step and use it inside postman's `Authoriation` header like `bearer <Token>`  and try to post some dishes on `https://localhost:3443/dishes` point, but what I get in responce is "You are not authorized to perform this operation!!" .

I thought maybe the problem is because of lacking OpenSSL installed on my Windowsh machin?
I also tried to dissable `FaceBook-Token-ID` by commenting the following lines in related files that ,aybe the error message is because of that?

```
config.js:

module.exports = {
    'secretKey': '12345-67890-09876-54321',
    'mongoUrl': 'mongodb://localhost:27017/conFusion'
    /*,
    'facebook': {
        clientId: 'Your App ID',
        clientSecret: 'Your App Secret'
    }
    */
}


user.js:

    //facebookId: String,


authenticate.js:

users.js:
/*
router.get('/facebook/token', passport.authenticate('facebook-token'), (req, res) => {
  if (req.user) {
    var token = authenticate.getToken({_id: req.user._id});
    res.statusCode = 200;
    res.setHeader('Content-Type', 'application/json');
    res.json({success: true, token: token, status: 'You are successfully logged in!'});
  }
});
*/


/*
exports.facebookPassport = passport.use(new FacebookTokenStrategy({
    clientID: config.facebook.clientId,
    clientSecret: config.facebook.clientSecret
}, (accessToken, refreshToken, profile, done) => {
    User.findOne({facebookId: profile.id}, (err, user) => {
        if (err) {
            return done(err, false);
        }
        if (!err && user !== null) {
            return done(null, user);
        }
        else {
            user = new User({ username: profile.displayName });
            user.facebookId = profile.id;
            user.firstname = profile.name.givenName;
            user.lastname = profile.name.familyName;
            user.save((err, user) => {
                if (err)
                    return done(err, false);
                else
                    return done(null, user);
            })
        }
    });
}
));
*/







```

**Comment by rezaee** [comment]
@zeeshan87 : Please help me to understand what is the problem?

**Comment by rezaee** [comment]
@zeeshan87 : Help!

**Comment by zeeshan87** [comment]
You can't register an admin user via the API as can be seen from users router. You have to manually set the admin flag to true. It's emulating the signup flow of users and you don't give them admin like privileges.
